#The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#Let us list the factors of the first seven triangle numbers:
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
#10: 1,2,5,10
#15: 1,3,5,15
#21: 1,3,7,21
#28: 1,2,4,7,14,28
#We can see that 28 is the first triangle number to have over five divisors.
#What is the value of the first triangle number to have over five hundred divisors?
divisors=0
a=1

while divisors<500:
    if divisors<500:
        divisors=0
    else:
        break
    a+=1
    for i in range (1,a):
        triangle_number=a*(a+1)//2
        sqrt_triangle_number=int(triangle_number**0.5)
    for c in range(1,sqrt_triangle_number+1):
        if triangle_number%c==0:
            divisors+=2
    if sqrt_triangle_number*sqrt_triangle_number== triangle_number:
        divisors-=1
print(triangle_number)
