#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

list=[1,2]
evenList=[]
n1, n2, nf=1, 2, 0
while nf<4000001:
    nf=n1+n2
    n1=n2
    n2=nf
    list.append(nf)
for i in list:
    if i%2==0:
        evenList.append(i)

print(sum(evenList))
